### ISSUE TITLE
Overly long timeout

### ISSUE THREAD

**Issue by jmstaley** [voucherifyio/voucherify-python-sdk#38]
I'm currently using the client and we've been having some problems with long running requests to the api timing out and causing our workers to exit.

In the process of investigating the problem i looked to see what the timeout in the client was. I noticed that there is a default timeout set `TIMEOUT = 30 * 1000`.  Requests requires that the timeout be set in [seconds](https://requests.readthedocs.io/en/master/user/quickstart/#timeouts) so the client is currently setting the timeout to be 30000 seconds or 500 minutes. This seems like an overly long default timeout.

It would be nice if the timeout could be configurable with a environment variable or via the Client init. Failing that just a sensible default.

**Comment by tpindel** [comment]
In the latest version, we introduced an option to configure timeout -> https://github.com/voucherifyio/voucherify-python-sdk/pull/41
