### ISSUE TITLE
Enable using validation sessions when redeeming a coupon

### ISSUE THREAD

**Issue by osamatier** [voucherifyio/voucherify-python-sdk#44]
To be able to use [validation sessions](https://docs.voucherify.io/reference/validation-session) with [redeem voucher](https://github.com/voucherifyio/voucherify-python-sdk#redeem-voucher).

**Comment by darekg11** [comment]
Hello @osamatier 
It is already possible to pass `session` property to both validation and redemption.
Please take a look at following example including both validation and redemption request with passed `session`:
```
import pprint
from voucherify import Client as voucherifyClient

# Validate with session
voucherify = voucherifyClient(
  application_id="APP_ID",
  client_secret_key="SECRET",
)

customer = {
  "source_id": "alice.morgan",
  "name": "Alice Morgan",
  "email": "alice@morgan.com",
  "description": "",
  "metadata": {
    "locale": "en-GB",
    "shoeSize": 5,
    "favourite_brands": "Armani"
  }
}
session = {
  "type": "LOCK",
  "key": "ssn_yQGMTeKBSw8OOuFPwlBEjzGy8d8VA9Ts",
  "ttl": 7,
  "ttl_unit": "DAYS"
}

order = {
  "amount": 100000
}

payload = {
  "customer": customer,
  "session": session,
  "order": order
}
result = voucherify.validations.validateVoucher("TEST-01", payload)
pprint.pprint(result)


# Reedem with session
payload["voucher"] = "TEST-01"
payload["session"] = {
  "type": "LOCK",
  "key": "ssn_yQGMTeKBSw8OOuFPwlBEjzGy8d8VA9Ts"
}
result_redemption = voucherify.redemptions.redeem(payload)
pprint.pprint(result_redemption)
```

Is there anything that I am missing?

**Comment by osamatier** [comment]
That's great!  thank you!

**Comment by darekg11** [comment]
@osamatier Additionally we are working on a new SDK version with added method to delete sessions without the need to make a redemption, I am talking about this API method:  
https://docs.voucherify.io/reference/release-validation-session

**Comment by darekg11** [comment]
Version `2.2.2` has been released with new method allowing to remove validation session without the need to make a redemption.

I am closing this issue, please feel free to reopen if you feel like something is still missing
